### ISSUE TITLE
Hi, Terjeio, greetings to you. My partner and I are currently DIYing a lathe.

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/STM32F4xx#118]
We plan to use your grblhal as a controller based on F4. We are very confused about the issue of spindle synchronized threading because we have little knowledge of electronics. We have enabled #define SPINDLE_SYNC_ENABLE 1 and defined 

#define SPINDLE_INDEX_PORT GPIOB
#define SPINDLE_INDEX_PIN 15

#define SPINDLE_PULSE_PORT GPIOB
#define SPINDLE_PULSE_PIN 14

I don't know what to do for the next hardware connection, and I don't know why you need two inputs. In my personal understanding, for threading on a lathe, we only need the spindle speed and feed speed to be proportional to advance the tool. So, before machining the thread, do we need to know whether the spindle speed has reached the target? I saw someone on YouTube stick a magnet on the lathe spindle to measure the spindle speed.

![车床](https://user-images.githubusercontent.com/108179425/233765210-708f2ab7-5c15-45e6-82e3-e3d44423756b.jpg)

**Comment by terjeio** [comment]
You cannot make a thread in a single pass (even if you have a very rigid lathe?), and if it is a multi start thread surely not. E.g. spindle RPM will likely change a bit when cutting starts. And how do you know that the commanded RPM is the same as the actual RPM?
So, to make a thread you need to know where the tool top is in relation to the spindle at all times - and adjust its position dynamically if it deviates from where it should be.

grblHAL uses two inputs for that: the spindle index signal which provides a single pulse per revolution and a signal that provides a number of pulses per revolution used to calculate the RPM and angular position.
The index signal is used to trigger Z motion, the calulated angular position as input to a feedback loop (PID) that is used to adjust the feed rate so that the tool tip ends up where it should be at all times.
