### ISSUE TITLE
I want to add some pins as button inputs, so that when the user presses a button, a message is sent to the host computer, triggering custom G-code defined by the user.

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/STM32F4xx#157]
#define AUXOUTPUT0_PORT    GPIOE
#define AUXOUTPUT0_PIN     7

The approach of waiting for input may not be suitable for my needs. Of course, regarding the host computer part, I will implement it myself. I mainly want to ask for your opinion. I am just concerned that directly adding without some reasonable method (like the plugin you mentioned?) may cause instability or other unexpected situations in the core part of grblhal.

**Comment by terjeio** [comment]
A plugin that claims the pin and register an interrupt handler for it is the way to do it. Note that the message should be sent from the foreground process to ensure it is not intermingled with other output - never from the interrupt handler.
The [Bluetooth plugin](https://github.com/grblHAL/Plugins_Bluetooth/) uses this approach and it does not interfere with the core (other than switching input streams when called for).

FYI the [Macros plugin](https://github.com/grblHAL/Plugin_keypad/blob/master/macros.c) might also provide some insight if you want to write a plugin, or maybe you can even use it as-is since it executes custom gcode snippets on keypresses. And if the customer has a SD-card attached [more options are available](https://github.com/grblHAL/core/wiki/Expressions-and-flow-control)...
