### ISSUE TITLE
Issue with Black Pill

### ISSUE THREAD

**Issue by troth530** [grblHAL/STM32F4xx#3]
Hi, I use a typical gCode sender (commercial) and get this error.  
Is there some gCode standard that is being used for the core or is this a driver issue?
Is this because of advanced gCode commands and is there a way to disable to be compatible with typical senders?
Thanks!

During a typical jog or any movement I get this error.
error:9
G-code locked out during alarm or jog state.

**Comment by terjeio** [comment]
Error 9 is due to the controller beeing in an alarm state. This could be due to grblHAL defaulting to normally closed (NC) switches, in new setups typically because the reset input is not connected to ground. Check this [wiki page](https://github.com/grblHAL/core/wiki/First-Run-Grbl-Settings) for tips.

**Comment by troth530** [comment]
@terjeio  thank you for all of your hard work. Issue is closed.
