### ISSUE TITLE
How does ESTOP_ENABLE work?

### ISSUE THREAD

**Issue by muhammadelmogy** [grblHAL/STM32F4xx#84]
I see there is a definition in my_machine.h for ESTOP_ENABLE commented by default, I want to know what do I expect when 
un-comment this line?

I want to only stop the steppers without disabling them (stepper drivers still active and enabled) so I do not lose the current position, also I want to stop the spindle.

Will enabling ESTOP_ENABLE do that?

**EDIT**
_It seems that ESTOP_ENABLE is defined in my_machine.h only for IMXRT1062 and not for stm32f4XX
I am going to use STM32f411 controller!_

**Comment by terjeio** [comment]
> Will enabling ESTOP_ENABLE do that?

No. But you can keep the steppers powered - there are settings for that, $1 and $37. If estop or reset is called for during motion you are likely to loose position due to the fact that the masses involved in motion cannot decelerate to a stop in zero time. However, if estop or reset is issued during no motion you can safely keep the homed position - there is a setting flag for that in $22:

![image](https://user-images.githubusercontent.com/20260062/181436265-c27eed9e-0ef1-4128-b000-6d3b477f7721.png)

> It seems that ESTOP_ENABLE is defined in my_machine.h only for IMXRT1062 and not for stm32f4XX

It is defined here:
https://github.com/grblHAL/STM32F4xx/blob/7287a200964023ae3c37738abd5dc78350056be0/Inc/my_machine.h#L78-L79

The default is not the same as for iMXRT1062 - to keep backwards compatibility.
