### ISSUE TITLE
I don't know how to get the 6 axis compilation to pass, got an error

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/STM32F4xx#94]
I have noticed that some users who purchased the grblhal control board are not used for cnc engraving machine, but pure motor control, so I tried to compile 6 axes, but encountered an error,
I defined N_AXIS 6 in grbl-config.h,
cnc3040_map.h is enabled, and M5 is defined
, but encountered a compilation error (the five-axis can be compiled and passed)
![dddd](https://user-images.githubusercontent.com/108179425/191652395-5bf51f86-ee71-4b10-bf1e-162f7af920b0.png)

**Comment by terjeio** [comment]
> cnc3040_map.h is enabled, and M5 is defined

You have modified the map file?

**Comment by hanke-cnc** [comment]
> > cnc3040_map.h is enabled, and M5 is defined
> 
> You have modified the map file?

no, i just defined m5
![DD](https://user-images.githubusercontent.com/108179425/191670002-dd35a858-329d-4d3e-b18a-e21d45dc2239.png)

**Comment by hanke-cnc** [comment]
Five axes can be perfectly compiled through

**Comment by terjeio** [comment]
>>     You have modified the map file?

> no, i just defined m5

Well, that is a modification...

There are two missing commas, [here](https://github.com/grblHAL/core/blob/c7c64366e39f8bcab612d24f9196ab9d6d7e58ad/stepdir_map.h#L84) and [here](https://github.com/grblHAL/core/blob/c7c64366e39f8bcab612d24f9196ab9d6d7e58ad/stepdir_map.h#L163). I you beat me to it because I am about to update this file to support 8 axes by generating the file programmatically.

**Comment by terjeio** [comment]
Use this file, there is a couple of further typos/bugs in the original.

[stepdir_map.zip](https://github.com/grblHAL/STM32F4xx/files/9623291/stepdir_map.zip)
